---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart pm2-mdt.service
  ansible.builtin.systemd:
    name: "pm2-{{ life_rpg_user }}.service"
    state: restarted
    enabled: true
  listen: restart pm2-mdt
