#!/bin/bash
# Copyright (c) 2025 MikeT LLC. All rights reserved.
#
# deploy-autofs-count-zero.sh
# Deploy autofs configuration for SMB mounts on count-zero
# Run this script ON count-zero (will prompt for sudo password)

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${CYAN}[$(date '+%H:%M:%S')]${NC} $1"; }
success() { echo -e "${GREEN}[$(date '+%H:%M:%S')] ✓${NC} $1"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] ⚠${NC} $1"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ✗${NC} $1"; }

# Configuration
SMB_SERVER="motoko"
SMB_USERNAME="mdt"
SMB_ENV_FILE="${HOME}/.mkt/mounts.env"
AUTOFS_MOUNT_BASE="/mnt/motoko"
AUTOFS_TIMEOUT=300
AUTOFS_MASTER="/etc/auto_master"
AUTOFS_MAP="/etc/auto.motoko"

echo "=========================================="
echo "Autofs Deployment for count-zero"
echo "=========================================="
echo ""

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    error "This script requires sudo privileges"
    echo "Please run: sudo $0"
    exit 1
fi

# Step 1: Check prerequisites
log "1. Checking prerequisites..."

if [ ! -f "$SMB_ENV_FILE" ]; then
    error "Secrets file missing: $SMB_ENV_FILE"
    echo "   Run: ansible-playbook -i inventory/hosts.yml playbooks/secrets-sync.yml --limit count-zero"
    exit 1
fi
success "Secrets file exists"

# Read SMB password
set -o allexport
source "$SMB_ENV_FILE"
set +o allexport

if [ -z "${SMB_PASSWORD:-}" ]; then
    error "SMB_PASSWORD not found in secrets file"
    exit 1
fi

# URL-encode password
SMB_PASSWORD_ENCODED=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$SMB_PASSWORD', safe=''))")
success "Password loaded and encoded"
echo ""

# Step 2: Clean up old manual mounts
log "2. Cleaning up old manual mounts..."

# Unmount old mounts (as the user, not root)
USER_HOME=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)
if [ -n "$USER_HOME" ]; then
    su - "${SUDO_USER:-$USER}" -c "umount $USER_HOME/.mkt/flux $USER_HOME/.mkt/space $USER_HOME/.mkt/time 2>/dev/null || true"
    success "Old mounts unmounted"
    
    # Remove old LaunchAgent
    su - "${SUDO_USER:-$USER}" -c "launchctl unload $USER_HOME/Library/LaunchAgents/com.miket.storage-connect.plist 2>/dev/null || true"
    success "Old LaunchAgent removed"
else
    warn "Could not determine user home directory"
fi
echo ""

# Step 3: Create mount base directory
log "3. Creating mount base directory..."
mkdir -p "$AUTOFS_MOUNT_BASE"
chmod 755 "$AUTOFS_MOUNT_BASE"
success "Mount base created: $AUTOFS_MOUNT_BASE"
echo ""

# Step 4: Configure autofs master
log "4. Configuring autofs master..."

if ! grep -q "^${AUTOFS_MOUNT_BASE} " "$AUTOFS_MASTER"; then
    echo "${AUTOFS_MOUNT_BASE} ${AUTOFS_MAP} --timeout=${AUTOFS_TIMEOUT}" >> "$AUTOFS_MASTER"
    success "Added entry to $AUTOFS_MASTER"
else
    success "Entry already exists in $AUTOFS_MASTER"
fi
echo ""

# Step 5: Create autofs map
log "5. Creating autofs map..."

cat > "$AUTOFS_MAP" <<EOF
# Autofs map for motoko SMB shares
# Auto-generated by deploy-autofs-count-zero.sh - do not edit manually
#
# Shares are mounted on-demand when accessed, unmounted after ${AUTOFS_TIMEOUT}s idle
# This avoids stale mounts that break Time Machine and other services
#
flux -fstype=smbfs,soft,noowners,nosuid,rw ://${SMB_USERNAME}:${SMB_PASSWORD_ENCODED}@${SMB_SERVER}/flux
space -fstype=smbfs,soft,noowners,nosuid,rw ://${SMB_USERNAME}:${SMB_PASSWORD_ENCODED}@${SMB_SERVER}/space
time -fstype=smbfs,soft,noowners,nosuid,rw ://${SMB_USERNAME}:${SMB_PASSWORD_ENCODED}@${SMB_SERVER}/time
EOF

chmod 644 "$AUTOFS_MAP"
success "Autofs map created: $AUTOFS_MAP"
echo ""

# Step 6: Create user symlinks
log "6. Creating user symlinks..."

if [ -n "$USER_HOME" ]; then
    for share in flux space time; do
        LINK_PATH="$USER_HOME/$share"
        TARGET_PATH="$AUTOFS_MOUNT_BASE/$share"
        
        # Remove existing symlink or file
        su - "${SUDO_USER:-$USER}" -c "rm -f $LINK_PATH 2>/dev/null || true"
        
        # Create symlink
        su - "${SUDO_USER:-$USER}" -c "ln -s $TARGET_PATH $LINK_PATH"
        success "Created symlink: $LINK_PATH -> $TARGET_PATH"
    done
else
    warn "Could not create user symlinks (user home not found)"
fi
echo ""

# Step 7: Reload autofs
log "7. Reloading autofs configuration..."
automount -vc
success "Autofs configuration reloaded"
echo ""

# Step 8: Verify configuration
log "8. Verifying configuration..."

if grep -q "^${AUTOFS_MOUNT_BASE} " "$AUTOFS_MASTER"; then
    success "Autofs master entry verified"
else
    error "Autofs master entry not found"
fi

if [ -f "$AUTOFS_MAP" ]; then
    success "Autofs map file exists"
    echo "   Contents:"
    cat "$AUTOFS_MAP" | sed 's/^/   /'
else
    error "Autofs map file not found"
fi
echo ""

# Step 9: Test mounts
log "9. Testing mounts (on-demand)..."
if [ -n "$USER_HOME" ]; then
    echo "   Testing access to ~/space (this will trigger mount)..."
    su - "${SUDO_USER:-$USER}" -c "ls $USER_HOME/space >/dev/null 2>&1 && echo '   Mount successful' || echo '   Mount failed'"
    
    sleep 2
    if mount | grep -q "on ${AUTOFS_MOUNT_BASE}/space"; then
        success "Space share mounted successfully"
    else
        warn "Space share not mounted (may need to access it first)"
    fi
else
    warn "Skipping mount test (user home not found)"
fi
echo ""

echo "=========================================="
echo "Deployment Complete"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Test mounts: ls ~/space ~/flux ~/time"
echo "  2. Check mount status: mount | grep autofs"
echo "  3. Test Time Machine: tmutil status"
echo ""
success "Autofs deployment completed successfully!"

